# Generated by Django 5.1.1 on 2024-10-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chosens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosens',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
