# Generated by Django 5.1.1 on 2024-10-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chosens', '0002_chosens_is_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chosens',
        ),
    ]
