# Generated by Django 5.1.1 on 2024-10-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_chosens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chosens',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.RemoveField(
            model_name='chosens',
            name='is_added',
        ),
        migrations.AddField(
            model_name='chosens',
            name='quantit_added',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
