# Generated by Django 5.1.1 on 2024-10-31 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_chosens_options_remove_chosens_is_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chosens',
            name='quantit_added',
        ),
    ]
