# Generated by Django 5.1.1 on 2024-10-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
