# Generated by Django 5.1.1 on 2024-10-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dislikes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='is_disliked',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='likes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
