# Generated by Django 5.1.1 on 2024-10-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_dislikes_products_is_disliked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(null=True, upload_to='category_image'),
        ),
    ]
