# Generated by Django 5.1.1 on 2024-10-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_little',
            field=models.BooleanField(default=False),
        ),
    ]
